#!/bin/bash

# This can be used to run java cowthink as a command line utility on *nix systems.
# Downloaded the cowsay jar.
# Put this wrapper script in the same directory.
# Make this wrapper script executable: chmod +x cowsay
# Ensure the directory that contains this wrapper script is in your PATH.
#
# You must obviously have java installed.

BASEDIR=$(dirname "$0")
java -jar $BASEDIR/cowsay-1.0.3.jar --cowthink $@
